# Generated by Django 5.0.4 on 2024-08-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_documento',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
