# Generated by Django 5.0.4 on 2024-09-11 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambiente', '0001_initial'),
        ('muestra', '0001_initial'),
        ('tipo_servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=8)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('ambiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ambiente.ambiente')),
                ('muestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muestra.muestra')),
                ('tipo_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_servicios.tiposervicio')),
            ],
        ),
    ]
