# Generated by Django 5.0.4 on 2024-09-11 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detalle', '0001_initial'),
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_id_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detalle.detalle')),
                ('fk_id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio')),
            ],
        ),
    ]
