# Generated by Django 5.0.4 on 2024-09-04 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos', '0001_initial'),
        ('servicios', '0001_initial'),
        ('versiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Dato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos.dato')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicio')),
                ('versiones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='versiones.versione')),
            ],
        ),
    ]
