# Generated by Django 5.0.4 on 2024-09-04 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detalle', '0002_initial'),
        ('versiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='versiones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='versiones.versione'),
        ),
    ]
