# Generated by Django 5.0.4 on 2024-09-04 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle', '0003_initial'),
        ('variables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='valor',
        ),
        migrations.AddField(
            model_name='detalle',
            name='variables',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variables.variblesmodel'),
        ),
    ]
